CREATE TABLE iceberg_catalog.schema_name.table_1_name (
    log_timestamp VARCHAR,
    msg_timestamp TIMESTAMP,
    local_timestamp TIMESTAMP,
    session_index INT,
    session_id VARCHAR,
    app_server_address VARCHAR,
    application_id VARCHAR,
    log_level VARCHAR,
    session_label VARCHAR,
    activity_name VARCHAR,
    activity_duration INT,
    message VARCHAR,
    log_type VARCHAR,
    var_name VARCHAR,
    var_value VARCHAR,
    module_id_node_id VARCHAR,
    vpid INT,
    reconf INT,
    no_input_count INT,
    no_match_count INT,
    zone_id INT,
    insert_id BIGINT
);
CREATE TABLE iceberg_catalog.schema_name.table_2_name (
    call_timestamp TIMESTAMP,
    local_timestamp TIMESTAMP,
    record_id INT,
    session_id VARCHAR,
    call_id VARCHAR,
    uc_id VARCHAR,
    port_id INT,
    call_start_date INT,
    call_start_time INT,
    call_type INT,
    duration INT,
    application_name VARCHAR,
    originating_number VARCHAR,
    destination_number VARCHAR,
    redirected_number VARCHAR,
    reason_code VARCHAR,
    end_type INT,
    end_details VARCHAR,
    mpp VARCHAR,
    switch_or_proxy VARCHAR,
    tel_media_encryption VARCHAR,
    tel_protocol VARCHAR,
    connect_latency INT,
    first_prompt_latency INT,
    rtp_round_trip_time INT,
    rtp_send_jitter INT,
    rtp_send_packets INT,
    rtp_send_lost INT,
    rtp_rcv_jitter INT,
    rtp_rcv_packets INT,
    rtp_rcv_lost INT,
    vp_id INT,
    audio_codec VARCHAR,
    video_codec VARCHAR,
    video_frame_rate INT,
    video_bit_rate VARCHAR,
    video_screen_size VARCHAR,
    area_code INT,
    record_date INT,
    insert_date INT,
    insert_record_id INT,
    insert_id BIGINT,
    media_type INT,
    zone_id INT,
    receipt_requested INT,
    provider_name VARCHAR,
    provider_message VARCHAR,
    provider_status INT,
    sms_entry_id BIGINT,
    eml_entry_id BIGINT,
    created_date_time TIMESTAMP,
    id INT
);
INSERT INTO iceberg_catalog.schema_name.table_1_name (
    log_timestamp,
    msg_timestamp,
    local_timestamp,
    session_index,
    session_id,
    app_server_address,
    application_id,
    log_level,
    session_label,
    activity_name,
    activity_duration,
    message,
    log_type,
    var_name,
    var_value,
    module_id_node_id,
    vpid,
    reconf,
    no_input_count,
    no_match_count,
    zone_id,
    insert_id
)
SELECT
    json_extract_scalar(json_data, '$.logtimestamp') AS log_timestamp,
    from_iso8601_timestamp(json_extract_scalar(json_data, '$.msgtimestamp')) AS msg_timestamp,
    CAST(
        from_iso8601_timestamp(
            json_extract_scalar(json_data, '$.msgtimestamp')
        ) AT TIME ZONE 'America/Los_Angeles' AS TIMESTAMP
    ) AS local_timestamp,
    CAST(json_extract_scalar(json_data, '$.sessionindex') AS INT) AS session_index,
    json_extract_scalar(json_data, '$.sessionid') AS session_id,
    json_extract_scalar(json_data, '$.appserveraddress') AS app_server_address,
    json_extract_scalar(json_data, '$.applicationid') AS application_id,
    json_extract_scalar(json_data, '$.loglevel') AS log_level,
    json_extract_scalar(json_data, '$.sessionlabel') AS session_label,
    json_extract_scalar(json_data, '$.activityname') AS activity_name,
    CAST(json_extract_scalar(json_data, '$.activityduration') AS INT) AS activity_duration,
    json_extract_scalar(json_data, '$.message') AS message,
    json_extract_scalar(json_data, '$.logtype') AS log_type,
    json_extract_scalar(json_data, '$.varname') AS var_name,
    json_extract_scalar(json_data, '$.varvalue') AS var_value,
    json_extract_scalar(json_data, '$.moduleidnodeid') AS module_id_node_id,
    CAST(json_extract_scalar(json_data, '$.vpid') AS INT) AS vpid,
    CAST(json_extract_scalar(json_data, '$.reconf') AS INT) AS reconf,
    CAST(json_extract_scalar(json_data, '$.noinputcount') AS INT) AS no_input_count,
    CAST(json_extract_scalar(json_data, '$.nomatchcount') AS INT) AS no_match_count,
    CAST(json_extract_scalar(json_data, '$.zoneid') AS INT) AS zone_id,
    CAST(json_extract_scalar(json_data, '$.insertid') AS BIGINT) AS insert_id
FROM base_table;
INSERT INTO iceberg_catalog.schema_name.table_2_name (
    call_timestamp,
    local_timestamp,
    record_id,
    session_id,
    call_id,
    uc_id,
    port_id,
    call_start_date,
    call_start_time,
    call_type,
    duration,
    application_name,
    originating_number,
    destination_number,
    redirected_number,
    reason_code,
    end_type,
    end_details,
    mpp,
    switch_or_proxy,
    tel_media_encryption,
    tel_protocol,
    connect_latency,
    first_prompt_latency,
    rtp_round_trip_time,
    rtp_send_jitter,
    rtp_send_packets,
    rtp_send_lost,
    rtp_rcv_jitter,
    rtp_rcv_packets,
    rtp_rcv_lost,
    vp_id,
    audio_codec,
    video_codec,
    video_frame_rate,
    video_bit_rate,
    video_screen_size,
    area_code,
    record_date,
    insert_date,
    insert_record_id,
    insert_id,
    media_type,
    zone_id,
    receipt_requested,
    provider_name,
    provider_message,
    provider_status,
    sms_entry_id,
    eml_entry_id,
    created_date_time,
    id
)
SELECT
    from_iso8601_timestamp(json_extract_scalar(json_data, '$.calltimestamp')) AS call_timestamp,
    CAST(
        from_iso8601_timestamp(
            json_extract_scalar(json_data, '$.calltimestamp')
        ) AT TIME ZONE 'America/Los_Angeles' AS TIMESTAMP
    ) AS local_timestamp,
    CAST(json_extract_scalar(json_data, '$.recordid') AS INT) AS record_id,
    json_extract_scalar(json_data, '$.sessionid') AS session_id,
    json_extract_scalar(json_data, '$.callid') AS call_id,
    json_extract_scalar(json_data, '$.ucid') AS uc_id,
    CAST(json_extract_scalar(json_data, '$.portid') AS INT) AS port_id,
    CAST(json_extract_scalar(json_data, '$.callstartdate') AS INT) AS call_start_date,
    CAST(json_extract_scalar(json_data, '$.callstarttime') AS INT) AS call_start_time,
    CAST(json_extract_scalar(json_data, '$.calltype') AS INT) AS call_type,
    CAST(json_extract_scalar(json_data, '$.duration') AS INT) AS duration,
    json_extract_scalar(json_data, '$.applicationname') AS application_name,
    json_extract_scalar(json_data, '$.originatingnumber') AS originating_number,
    json_extract_scalar(json_data, '$.destinationnumber') AS destination_number,
    json_extract_scalar(json_data, '$.redirectednumber') AS redirected_number,
    json_extract_scalar(json_data, '$.reasoncode') AS reason_code,
    CAST(json_extract_scalar(json_data, '$.endtype') AS INT) AS end_type,
    json_extract_scalar(json_data, '$.enddetails') AS end_details,
    json_extract_scalar(json_data, '$.mpp') AS mpp,
    json_extract_scalar(json_data, '$.switchorproxy') AS switch_or_proxy,
    json_extract_scalar(json_data, '$.telmediaencryption') AS tel_media_encryption,
    json_extract_scalar(json_data, '$.telprotocol') AS tel_protocol,
    CAST(json_extract_scalar(json_data, '$.connectlatency') AS INT) AS connect_latency,
    CAST(json_extract_scalar(json_data, '$.firstpromptlatency') AS INT) AS first_prompt_latency,
    CAST(json_extract_scalar(json_data, '$.rtproundtriptime') AS INT) AS rtp_round_trip_time,
    CAST(json_extract_scalar(json_data, '$.rtpsendjitter') AS INT) AS rtp_send_jitter,
    CAST(json_extract_scalar(json_data, '$.rtpsendpackets') AS INT) AS rtp_send_packets,
    CAST(json_extract_scalar(json_data, '$.rtpsendlost') AS INT) AS rtp_send_lost,
    CAST(json_extract_scalar(json_data, '$.rtprcvjitter') AS INT) AS rtp_rcv_jitter,
    CAST(json_extract_scalar(json_data, '$.rtprcvpackets') AS INT) AS rtp_rcv_packets,
    CAST(json_extract_scalar(json_data, '$.rtprcvlost') AS INT) AS rtp_rcv_lost,
    CAST(json_extract_scalar(json_data, '$.vpid') AS INT) AS vp_id,
    json_extract_scalar(json_data, '$.audiocodec') AS audio_codec,
    json_extract_scalar(json_data, '$.videocodec') AS video_codec,
    CAST(json_extract_scalar(json_data, '$.videoframerate') AS INT) AS video_frame_rate,
    json_extract_scalar(json_data, '$.videobitrate') AS video_bit_rate,
    json_extract_scalar(json_data, '$.videoscreensize') AS video_screen_size,
    CAST(json_extract_scalar(json_data, '$.areacode') AS INT) AS area_code,
    CAST(json_extract_scalar(json_data, '$.recorddate') AS INT) AS record_date,
    CAST(json_extract_scalar(json_data, '$.insertdate') AS INT) AS insert_date,
    CAST(json_extract_scalar(json_data, '$.insertrecordid') AS INT) AS insert_record_id,
    CAST(json_extract_scalar(json_data, '$.insertid') AS BIGINT) AS insert_id,
    CAST(json_extract_scalar(json_data, '$.mediatype') AS INT) AS media_type,
    CAST(json_extract_scalar(json_data, '$.zoneid') AS INT) AS zone_id,
    CAST(json_extract_scalar(json_data, '$.receiptrequested') AS INT) AS receipt_requested,
    json_extract_scalar(json_data, '$.providername') AS provider_name,
    json_extract_scalar(json_data, '$.providermessage') AS provider_message,
    CAST(json_extract_scalar(json_data, '$.providerstatus') AS INT) AS provider_status,
    CAST(json_extract_scalar(json_data, '$.smsentryid') AS BIGINT) AS sms_entry_id,
    CAST(json_extract_scalar(json_data, '$.mlentryid') AS BIGINT) AS eml_entry_id,
    from_iso8601_timestamp(json_extract_scalar(json_data, '$.createddatetime')) AS created_date_time,
    CAST(json_extract_scalar(json_data, '$.id') AS INT) AS id
FROM base_table;
